# tasks file for git-lfs
---
- name: install | dependencies
  apt:
    name: "{{ git_lfs_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - git-lfs-install-dependencies
