# tasks file
---
- name: install | dependencies
  ansible.builtin.apt:
    name: "{{ git_lfs_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - git-lfs-install-dependencies

# TODO: Make use of git_config_info
- name: install | configure | check | before
  community.general.git_config:
    list_all: true
    scope: system
  register: _config_before
  tags:
    - git-lfs-install-debug

- name: install | configure
  ansible.builtin.command: >
    git lfs install --system
  changed_when: false
  tags:
    - git-lfs-install-configure

- name: install | configure | check | after
  community.general.git_config:
    list_all: true
    scope: system
  register: _config_after
  changed_when: _config_before.config_values != _config_after.config_values
  tags:
    - git-lfs-install-debug

- name: install | verify
  ansible.builtin.command: >
    git lfs version
  register: _verify_version
  changed_when: false
  tags:
    - configuration
    - git-lfs
    - git-lfs-install
    - git-lfs-install-verify
