# tasks file
---
- ansible.builtin.import_tasks: repository.yml
  tags:
    - configuration
    - git-lfs
    - git-lfs-repository

- ansible.builtin.import_tasks: install.yml
  tags:
    - configuration
    - git-lfs
    - git-lfs-install
