# tasks file
---
- name: repository
  ansible.builtin.import_tasks: repository.yml
  tags:
    - configuration
    - git-lfs
    - git-lfs-repository

- name: install
  ansible.builtin.import_tasks: install.yml
  tags:
    - configuration
    - git-lfs
    - git-lfs-install
