# tasks file for git-lfs
---
- include: repository.yml
  tags:
    - configuration
    - git-lfs
    - git-lfs-repository

- include: install.yml
  tags:
    - configuration
    - git-lfs
    - git-lfs-install
